### ISSUE TITLE
question about run Gramineae.py

### ISSUE THREAD

**Issue by luozzz-00** [xjtu-omics/IAGS#2]
when I run this Gramineae.py,
Error code 10009: License expired 2022-01-13
Traceback (most recent call last):
  File "Gramineae.py", line 31, in <module>
    ancestor_name, dup_copy_number, out_copy_number, ancestor_target_copy_number)
  File "/Users/luo/Desktop/IAGS/IAGS/models/MultiGGHPmodel.py", line 37, in MultiCopyGGHPmodel
    adjacency_matrix = ggap.ancestor_adjacency_matrix()
  File "/Users/luo/Desktop/IAGS/IAGS/inferringAncestorGenomeStructure/GGHP.py", line 224, in ancestor_adjacency_matrix
    for v in self.__m.getVars():
AttributeError: 'GGHP' object has no attribute '_GGHP__m'

I have modified the corresponding file path, how to solve this error？ 🥹

**Comment by 865699871** [comment]
It seems like the Gurobi license expired and GGHP model cannot run. You can go to Gurobi website. It's free for academic.

**Comment by taotaoyuan** [comment]
你解决了吗，这个问题
